fix: updated lint and smever

diff --git a/tasks/semver-release/semver.yaml b/tasks/semver-release/semver.yaml
--- a/tasks/semver-release/semver.yaml
+++ b/tasks/semver-release/semver.yaml
@@ -12,10 +12,16 @@ spec:
         memory: 128Mi
     workingDir: /workspace/source
   steps:
-    - script: |
-        #!/usr/bin/env sh
-        last_message="$(git log -1 --pretty=%B)"
-        echo $last_message
-        case $last_message in "fix:"*) echo "Contains SemVer release info" && return 0 ;; "feat:"*) echo "Contains SemVer release info" && return 0 ;; *)  echo "Missing SemVer release info" && return 0  ;; esac
-      image: alpine/git
-      name: semver-check
+  - script: |
+      #!/usr/bin/env sh
+      last_message="$(git log -1 --pretty=%B)"
+      echo $last_message
+      (
+      case $last_message in
+        "fix:"*) echo "Contains SemVer release info" && exit 0 ;;
+        "feat:"*) echo "Contains SemVer release info" && exit 0 ;;
+        *)  echo "Missing SemVer release info" && exit 1  ;;
+      esac
+      )
+    image: alpine/git
+    name: semver-check
